version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: job_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  bot:
    build: ./bot
    container_name: job_bot
    env_file:
      - .env
    depends_on:
      - postgres

  scraper:
    build: ./scraper
    container_name: job_scraper
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  pgdata:
